### ISSUE TITLE
Error on Key / Method naming clash

### ISSUE THREAD

**Issue by deanobarnett** [salesking/json_schema_tools#28]
## Issue

Defining a method on a model that has the same name as a key that has been passed causes an error.
## Steps to reproduce
1. Create a json schema model.
2. Define a method on the model called `foo`
3. Pass a key with the same name (`foo`) and any value.
4. Use `from_hash` to create an instance of the model
5. See a no method for nil class error at [this line](https://github.com/salesking/json_schema_tools/blob/master/lib/schema_tools/modules/attributes.rb#L93)

``` ruby
class Bar
  include SchemaTools::Modules::Attributes
  include SchemaTools::Modules::Validations
  include SchemaTools::Modules::AsSchema
  has_schema_attrs 'bar'
  validate_with 'bar'

  def foo
    # do something
  end
end

Bar.from_hash({ 'foo' => 'test value' })
```

**Comment by schorsch** [comment]
Thanks for the report. i setup a test which show that we simply ignore such cases. 

I think your problem is rather a missing field 'type' definition in your schema, as pointed out by your code ref. (or maybe my spec is wrong, since i am using an inline schema)

Still an interesting point , what would you expect in such cases: an error? a warning? I also added a todo in the attributes module: https://github.com/salesking/json_schema_tools/blob/master/lib/schema_tools/modules/attributes.rb#L41
